/**
 * menuTree.js — Configuration UNIQUE du menu latéral thématique.
 *
 * MENU_TREE : thèmes d'usage → items. Chaque item :
 *   { kind:"tool",      id, label, icon }              → ouvre un panneau existant (activateItem(id))
 *   { kind:"indicator", id (clé INDICATORS), icon }    → ouvre l'IndicatorModal pré-réglé
 *
 * INDICATORS : pour chaque indicateur, ses options satellite (dataset + index
 * backend exacts), la 1re étant conseillée. Ajouter un indicateur ou un outil
 * vectoriel = une ligne de plus ici, aucun autre changement.
 *
 * Les `icon` sont des COMPOSANTS Lucide React (voir src/icons.jsx) — pas d'emoji.
 */
import {
  IcLeaf, IcSprout, IcTreePine, IcTrees, IcDroplet, IcDroplets, IcWaves,
  IcThermometer, IcCloudRain, IcCloud, IcCloudFog, IcWind, IcBuilding,
  IcFlame, IcMountain, IcSnowflake, IcLandPlot, IcGrid, IcSparkles, IcWrench,
  IcFilm, IcRadar, IcNavigation, IcCube, IcDiff, IcCompare, IcTrendingUp,
  IcStack, IcBarChart, IcVenn, IcClassif, IcEdit, IcDatabase, IcServer,
  IcOSM, IcRulerTool, IcHexagon, IcCircleDot, IcPencil, IcSatellite, IcMap, IcUser, IcSun, IcImage, IcTable,
  IcFish, IcBoxes, IcGlobe, IcMoon,
} from "../icons";

// dataset + index EXACTS attendus par /api/gee/tiles (voir gee_routes.py)
export const INDICATORS = {
  // ── Imagerie brute (composites colorés) ──
  // `rawClouds: true` → masque nuages désactivé par défaut : sur une image
  // d'observation, fumées et panaches sont l'information, pas du bruit.
  RGBIMG: { title: "Image vraies couleurs (RVB)", icon: IcImage, desc: "Ce que verrait l'œil depuis l'orbite.",
            rawClouds: true,
            options: [{ dataset: "sentinel2", index: "RGB", label: "Sentinel-2", res: "10 m · 5 j" },
                      { dataset: "landsat", index: "RGB", label: "Landsat", res: "30 m · 16 j" },
                      { dataset: "modis_daily", index: "RGB", label: "MODIS journalier", res: "500 m · quotidien (~2-3 j)" },
                      { dataset: "modis_rgb", index: "RGB", label: "MODIS BRDF", res: "500 m · nettoyé (16 j, latence)" }] },
  IRCIMG: { title: "Infrarouge couleur (IRC)", icon: IcImage, desc: "Végétation en rouge — vigueur et stress.",
            rawClouds: true,
            options: [{ dataset: "sentinel2", index: "False Color (NIR)", label: "Sentinel-2", res: "10 m · 5 j" },
                      { dataset: "landsat", index: "False Color (NIR)", label: "Landsat", res: "30 m · 16 j" },
                      { dataset: "modis_daily", index: "False Color (NIR)", label: "MODIS journalier", res: "500 m · quotidien (~2-3 j)" },
                      { dataset: "modis_rgb", index: "False Color (NIR)", label: "MODIS BRDF", res: "500 m · nettoyé (16 j, latence)" }] },
  SWIRIMG: { title: "Composite SWIR — feux et brûlis", icon: IcFlame, desc: "Traverse la fumée : fronts de feu et surfaces brûlées.",
            rawClouds: true,
            options: [{ dataset: "sentinel2", index: "SWIR (feux)", label: "Sentinel-2", res: "20 m · 5 j" },
                      { dataset: "landsat", index: "SWIR (feux)", label: "Landsat", res: "30 m · 16 j" }] },
  // ── Végétation ──
  NDVI:  { title: "NDVI — indice de végétation", icon: IcLeaf, desc: "Vigueur et densité de la végétation.",
           options: [{ dataset: "sentinel2", index: "NDVI", label: "Sentinel-2", res: "10 m · 5 j" },
                     { dataset: "landsat", index: "NDVI", label: "Landsat", res: "30 m · 16 j" },
                     { dataset: "modis_ndvi", index: "NDVI", label: "MODIS", res: "500 m · 16 j" }] },
  EVI:   { title: "EVI — végétation (dense)", icon: IcLeaf, desc: "Comme NDVI, moins saturé en forte biomasse.",
           options: [{ dataset: "sentinel2", index: "EVI", label: "Sentinel-2", res: "10 m" }] },
  SAVI:  { title: "SAVI — végétation (sol nu)", icon: IcSprout, desc: "Végétation en milieu peu couvert.",
           options: [{ dataset: "sentinel2", index: "SAVI", label: "Sentinel-2", res: "10 m" }] },
  GNDVI: { title: "GNDVI — chlorophylle", icon: IcSprout, desc: "Sensible à la chlorophylle (canal vert).",
           options: [{ dataset: "sentinel2", index: "GNDVI", label: "Sentinel-2", res: "10 m" },
                     { dataset: "landsat", index: "GNDVI", label: "Landsat", res: "30 m" }] },
  NDRE:  { title: "NDRE — vigueur (red-edge)", icon: IcSprout, desc: "Stress/vigueur fine, agriculture.",
           options: [{ dataset: "sentinel2", index: "NDRE", label: "Sentinel-2", res: "10 m" }] },
  // ── Forêt & canopée ──
  CANOPY: { title: "Hauteur de canopée", icon: IcTreePine, desc: "Hauteur des arbres (Meta / Global Forest Watch ~1 m).",
           options: [{ dataset: "canopy_height", index: "Hauteur canopée", label: "Meta / GFW 2020", res: "~1 m", static: true }] },
  FOREST: { title: "Forêt (Global Forest Watch)", icon: IcTrees, desc: "Couverture, perte et gain forestiers (Hansen/GFW).",
           options: [{ dataset: "hansen", index: "Couverture forêt 2000", label: "Couverture 2000", res: "30 m", static: true },
                     { dataset: "hansen", index: "Perte forêt", label: "Perte de forêt", res: "30 m", static: true },
                     { dataset: "hansen", index: "Gain forêt", label: "Gain de forêt", res: "30 m", static: true }] },
  // ── Eau & humidité ──
  NDWI:  { title: "NDWI — eau", icon: IcDroplet, desc: "Détection des surfaces en eau.",
           options: [{ dataset: "sentinel2", index: "NDWI", label: "Sentinel-2", res: "10 m" },
                     { dataset: "landsat", index: "NDWI", label: "Landsat", res: "30 m" }] },
  MNDWI: { title: "MNDWI — eau (urbain)", icon: IcDroplet, desc: "Meilleure détection eau en ville.",
           options: [{ dataset: "sentinel2", index: "MNDWI", label: "Sentinel-2", res: "10 m" },
                     { dataset: "landsat", index: "MNDWI", label: "Landsat", res: "30 m" }] },
  NDMI:  { title: "NDMI — humidité végétation", icon: IcDroplet, desc: "Stress hydrique de la végétation.",
           options: [{ dataset: "sentinel2", index: "NDMI", label: "Sentinel-2", res: "10 m" }] },
  NDCI:  { title: "NDCI — qualité de l'eau", icon: IcDroplet, desc: "Chlorophylle des plans d'eau.",
           options: [{ dataset: "sentinel2", index: "NDCI", label: "Sentinel-2", res: "10 m" }] },
  JRC_WATER: { title: "Eaux de surface (JRC)", icon: IcWaves, desc: "Occurrence historique des eaux.",
           options: [{ dataset: "jrc_water", index: "Occurrence", label: "JRC", res: "30 m", static: true }] },
  SMAP:  { title: "Humidité du sol (SMAP)", icon: IcDroplets, desc: "Humidité de surface du sol.",
           options: [{ dataset: "smap", index: "Humidité du sol", label: "SMAP", res: "~10 km" }] },
  // ── Climat & température ──
  LST:   { title: "Température de surface (LST)", icon: IcThermometer, desc: "Température du sol (°C).",
           options: [{ dataset: "landsat", index: "LST (température)", label: "Landsat", res: "30 m" },
                     { dataset: "modis_lst", index: "LST Jour", label: "MODIS jour", res: "1 km" }] },
  AIRTEMP: { title: "Température de l'air (ERA5)", icon: IcThermometer, desc: "Température atmosphérique.",
           options: [{ dataset: "era5", index: "Température air", label: "ERA5", res: "11 km" }] },
  PRECIP: { title: "Précipitations (CHIRPS)", icon: IcCloudRain, desc: "Cumul de pluie sur la période.",
           options: [{ dataset: "chirps", index: "Précipitations (cumul)", label: "CHIRPS", res: "5 km" }] },
  ET:    { title: "Évapotranspiration", icon: IcDroplets, desc: "Bilan hydrique (MODIS).",
           options: [{ dataset: "modis_et", index: "Évapotranspiration", label: "MODIS", res: "500 m" }] },
  // ── Qualité de l'air ──
  NO2:   { title: "Dioxyde d'azote (NO₂)", icon: IcWind, desc: "Pollution NO₂ (trafic/industrie).",
           options: [{ dataset: "sentinel5p", index: "NO₂", label: "Sentinel-5P", res: "~7 km" }] },
  CO:    { title: "Monoxyde de carbone (CO)", icon: IcWind, desc: "Colonne de CO.",
           options: [{ dataset: "sentinel5p", index: "CO", label: "Sentinel-5P", res: "~7 km" }] },
  CH4:   { title: "Méthane (CH₄)", icon: IcCloudFog, desc: "Concentration de méthane.",
           options: [{ dataset: "sentinel5p", index: "CH₄", label: "Sentinel-5P", res: "~7 km" }] },
  O3:    { title: "Ozone (O₃)", icon: IcCloud, desc: "Colonne d'ozone.",
           options: [{ dataset: "sentinel5p", index: "O₃", label: "Sentinel-5P", res: "~7 km" }] },
  AER:   { title: "Aérosols", icon: IcCloudFog, desc: "Indice d'aérosols absorbants.",
           options: [{ dataset: "sentinel5p", index: "Aérosols (AI)", label: "Sentinel-5P", res: "~7 km" }] },
  // ── Urbain & sols ──
  NDBI:  { title: "Bâti (NDBI)", icon: IcBuilding, desc: "Surfaces bâties.",
           options: [{ dataset: "sentinel2", index: "NDBI", label: "Sentinel-2", res: "10 m" }] },
  BSI:   { title: "Sol nu (BSI)", icon: IcLandPlot, desc: "Sols nus / imperméabilisés.",
           options: [{ dataset: "sentinel2", index: "BSI", label: "Sentinel-2", res: "10 m" },
                     { dataset: "landsat", index: "BSI", label: "Landsat", res: "30 m" }] },
  WORLDCOVER: { title: "Occupation du sol (ESA WorldCover)", icon: IcLandPlot, desc: "Carte d'occupation du sol ESA WorldCover 2021 (11 classes).",
           options: [{ dataset: "worldcover", index: "Occupation du sol", label: "ESA WorldCover 2021", res: "10 m", static: true }] },
  VIIRS: { title: "Lumières nocturnes", icon: IcSparkles, desc: "Activité humaine (radiance de nuit).",
           options: [{ dataset: "viirs", index: "Radiance nocturne", label: "VIIRS", res: "500 m" }] },
  POPULATION: { title: "Densité de population", icon: IcUser, desc: "Population maillée (habitants/km²) — époque la plus récente.",
           options: [{ dataset: "gpw_pop", index: "Densité de population", label: "GPW v4.11 (CIESIN)", res: "~1 km · 2020", static: true },
                     { dataset: "ghsl_pop", index: "Densité de population", label: "GHSL (JRC)", res: "100 m · 1975-2030" }] },
  BUILT: { title: "Surface bâtie (GHSL)", icon: IcBuilding, desc: "Emprise bâtie (% de la cellule) — millésimes 1975-2030.",
           options: [{ dataset: "ghsl_built", index: "Surface bâtie", label: "GHSL (JRC)", res: "100 m · 1975-2030" }] },
  SMOD: { title: "Degré d'urbanisation (GHSL)", icon: IcBuilding, desc: "Ville / périurbain / rural (SMOD) — millésimes 1975-2030.",
           options: [{ dataset: "ghsl_smod", index: "Degré d'urbanisation", label: "GHSL SMOD (JRC)", res: "1 km · 1975-2030" }] },
  DYNWORLD: { title: "Occupation du sol temps réel", icon: IcLandPlot, desc: "Dynamic World — 9 classes, quasi temps réel (Sentinel-2).",
           options: [{ dataset: "dynamicworld", index: "Occupation du sol (DW)", label: "Dynamic World (Google)", res: "10 m · ~5 j" }] },
  // ── Lot B — Risques / feux ──
  BURNED: { title: "Zones brûlées", icon: IcFlame, desc: "Surfaces incendiées (MODIS MCD64A1).",
           options: [{ dataset: "burned", index: "Zones brûlées", label: "MODIS", res: "500 m · mensuel" }] },
  FIRMS: { title: "Feux actifs", icon: IcFlame, desc: "Foyers de chaleur quasi temps réel (FIRMS).",
           options: [{ dataset: "firms", index: "Feux actifs", label: "FIRMS", res: "1 km · quotidien" }] },
  SMOKE: { title: "Panache de fumée", icon: IcCloudFog, desc: "Dispersion de fumée d'incendie (PM2.5/aérosols). CAMS = temps réel (feux actuels) ; GEOS-CF = études de cas 2022-2026. Animable jour par jour.",
           options: [{ dataset: "cams", index: "PM2.5 (fumée)", label: "PM2.5 — CAMS (temps réel)", res: "44 km · quotidien, à jour" },
                     { dataset: "cams", index: "Fumée (carbone organique)", label: "Fumée OC — CAMS (temps réel)", res: "44 km · quotidien" },
                     { dataset: "cams", index: "Aérosols (AOD)", label: "Aérosols AOD — CAMS (temps réel)", res: "44 km · quotidien" },
                     { dataset: "geos_cf", index: "PM2.5 (fumée)", label: "PM2.5 — GEOS-CF (2022-2026)", res: "27 km · études de cas" },
                     { dataset: "geos_cf", index: "Carbone suie (BC)", label: "Carbone suie — GEOS-CF", res: "27 km · 2022-2026" },
                     { dataset: "geos_cf", index: "Carbone organique (OC)", label: "Carbone organique — GEOS-CF", res: "27 km · 2022-2026" }] },
  // ── Lot C — Sols / agriculture ──
  SOC: { title: "Carbone organique du sol", icon: IcSprout, desc: "Stock de carbone / fertilité (OpenLandMap).",
           options: [{ dataset: "soil_soc", index: "Carbone organique", label: "OpenLandMap", res: "250 m", static: true }] },
  SOILPH: { title: "pH du sol", icon: IcDroplet, desc: "Acidité du sol (OpenLandMap).",
           options: [{ dataset: "soil_ph", index: "pH du sol", label: "OpenLandMap", res: "250 m", static: true }] },
  CLAY: { title: "Teneur en argile", icon: IcLandPlot, desc: "Texture du sol — % argile (OpenLandMap).",
           options: [{ dataset: "soil_clay", index: "Teneur en argile", label: "OpenLandMap", res: "250 m", static: true }] },
  // ── Lot D — Végétation : productivité ──
  GPP: { title: "Productivité végétale (GPP)", icon: IcLeaf, desc: "Photosynthèse brute (MODIS MOD17).",
           options: [{ dataset: "modis_gpp", index: "Productivité (GPP)", label: "MODIS", res: "500 m · 8 j" }] },
  LAIFAPAR: { title: "LAI / FAPAR", icon: IcTrees, desc: "Densité foliaire et rayonnement absorbé (MODIS).",
           options: [{ dataset: "modis_lai", index: "LAI", label: "MODIS LAI", res: "500 m · 4 j" },
                     { dataset: "modis_lai", index: "FAPAR", label: "MODIS FAPAR", res: "500 m · 4 j" }] },
  BIOMASS: { title: "Biomasse aérienne", icon: IcTrees, desc: "Stock de carbone forestier (GEDI L4B).",
           options: [{ dataset: "gedi_agb", index: "Biomasse aérienne", label: "GEDI", res: "1 km", static: true }] },
  // ── GEDI — LiDAR spatial NASA (25 m, ±51,6° lat) ──
  GEDI_CANOPY: { title: "GEDI — Hauteur de canopée (LiDAR)", icon: IcTreePine, desc: "Hauteur des arbres par LiDAR spatial (RH98).",
           options: [{ dataset: "gedi_l2a", index: "Hauteur canopée (RH98)", label: "GEDI L2A", res: "25 m · mensuel" }] },
  GEDI_ELEV: { title: "GEDI — Élévation du terrain (LiDAR)", icon: IcMountain, desc: "Altitude du sol vue sous le couvert.",
           options: [{ dataset: "gedi_l2a", index: "Élévation terrain", label: "GEDI L2A", res: "25 m · mensuel" }] },
  GEDI_COVER: { title: "GEDI — Couverture de canopée", icon: IcTrees, desc: "Fraction de couvert arboré (%).",
           options: [{ dataset: "gedi_l2b", index: "Couverture canopée", label: "GEDI L2B", res: "25 m · mensuel" }] },
  GEDI_PAI: { title: "GEDI — Indice de surface foliaire (PAI)", icon: IcLeaf, desc: "Densité foliaire, structure du couvert.",
           options: [{ dataset: "gedi_l2b", index: "Indice foliaire (PAI)", label: "GEDI L2B", res: "25 m · mensuel" }] },
  GEDI_AGB: { title: "GEDI — Biomasse aérienne (25 m)", icon: IcTrees, desc: "Carbone forestier à l'empreinte (Mg/ha).",
           options: [{ dataset: "gedi_l4a", index: "Biomasse aérienne (25m)", label: "GEDI L4A", res: "25 m · mensuel" }] },
  // ── Lot E — Climat / énergie ──
  SOLAR: { title: "Rayonnement solaire", icon: IcSun, desc: "Potentiel photovoltaïque (ERA5).",
           options: [{ dataset: "era5_solar", index: "Rayonnement solaire", label: "ERA5", res: "~11 km · mensuel" }] },
  WIND: { title: "Vitesse du vent", icon: IcWind, desc: "Potentiel éolien à 10 m (ERA5).",
           options: [{ dataset: "era5_wind", index: "Vitesse du vent", label: "ERA5", res: "~11 km · mensuel" }] },
  GPMPRECIP: { title: "Précipitations (GPM)", icon: IcCloudRain, desc: "Précipitations mensuelles (GPM IMERG).",
           options: [{ dataset: "gpm", index: "Précipitations (GPM)", label: "GPM IMERG", res: "~11 km · mensuel" }] },
  SNOW: { title: "Couverture neigeuse", icon: IcSnowflake, desc: "Manteau neigeux (MODIS MOD10A1).",
           options: [{ dataset: "modis_snow", index: "Neige", label: "MODIS", res: "500 m · quotidien" }] },
  // ── Lot F/G — Océanographie ──
  BATHY: { title: "Bathymétrie & relief sous-marin", icon: IcMountain, desc: "Profondeur des océans + altitude des terres (ETOPO1).",
           options: [{ dataset: "etopo", index: "Relief & bathymétrie", label: "ETOPO1", res: "~1.8 km", static: true }] },
  SST:   { title: "Température de surface de la mer", icon: IcThermometer, desc: "SST — canicules marines, El Niño, suivi climatique.",
           options: [{ dataset: "modis_ocean", index: "SST (MODIS)", label: "MODIS-Aqua", res: "~4 km · quotidien" },
                     { dataset: "oisst", index: "SST (OISST)", label: "NOAA OISST", res: "~27 km · quotidien" }] },
  SSTANOM: { title: "Anomalie de SST (canicule marine)", icon: IcTrendingUp, desc: "Écart à la normale : détecte les vagues de chaleur océaniques.",
           options: [{ dataset: "oisst", index: "Anomalie SST", label: "NOAA OISST", res: "~27 km · quotidien" }] },
  CHLORO: { title: "Chlorophylle-a", icon: IcSprout, desc: "Biomasse phytoplanctonique — productivité, efflorescences.",
           options: [{ dataset: "modis_ocean", index: "Chlorophylle-a", label: "MODIS-Aqua", res: "~4 km · quotidien" },
                     { dataset: "viirs_ocean", index: "Chlorophylle-a", label: "VIIRS", res: "~4 km · quotidien" }] },
  TURBIDITY: { title: "Matières en suspension (turbidité)", icon: IcDroplets, desc: "Charge particulaire côtière — proxy carbone organique (POC).",
           options: [{ dataset: "modis_ocean", index: "Matières en suspension", label: "MODIS-Aqua", res: "~4 km · quotidien" }] },
  CURRENTS: { title: "Courants marins", icon: IcNavigation, desc: "Vitesse des courants de surface (modèle HYCOM).",
           options: [{ dataset: "hycom_vel", index: "Courants marins", label: "HYCOM", res: "~9 km · quotidien" }] },
  OCEANWIND: { title: "Vent océanique", icon: IcWind, desc: "Vent à 10 m au-dessus des mers (ERA5).",
           options: [{ dataset: "era5_ocean_wind", index: "Vent océanique", label: "ERA5", res: "~31 km · horaire" }] },
  SALINITY: { title: "Salinité de surface", icon: IcDroplet, desc: "Salinité des eaux de surface (modèle HYCOM).",
           options: [{ dataset: "hycom_sal", index: "Salinité de surface", label: "HYCOM", res: "~9 km · quotidien" }] },
  SEAICE: { title: "Glace de mer", icon: IcSnowflake, desc: "Concentration de banquise (%).",
           options: [{ dataset: "oisst", index: "Glace de mer", label: "NOAA OISST", res: "~27 km · quotidien" }] },
  CORAL: { title: "Récifs coralliens", icon: IcFish, desc: "Emprise des récifs (Allen Coral Atlas).",
           options: [{ dataset: "coral", index: "Récifs coralliens", label: "Allen Coral Atlas", res: "~5 m", static: true }] },
  MANGROVE: { title: "Mangroves", icon: IcTrees, desc: "Forêts de mangrove de référence (2000).",
           options: [{ dataset: "mangrove", index: "Mangroves", label: "Global Mangrove Forests", res: "30 m", static: true }] },
  // ── Risques & feux ──
  NBR:   { title: "Ratio de brûlage (NBR)", icon: IcFlame, desc: "Zones brûlées / sévérité de feu.",
           options: [{ dataset: "sentinel2", index: "NBR", label: "Sentinel-2", res: "10 m" },
                     { dataset: "landsat", index: "NBR", label: "Landsat", res: "30 m" }] },
  NDSI:  { title: "Neige (NDSI)", icon: IcSnowflake, desc: "Couverture neigeuse.",
           options: [{ dataset: "sentinel2", index: "NDSI", label: "Sentinel-2", res: "10 m" },
                     { dataset: "landsat", index: "NDSI", label: "Landsat", res: "30 m" }] },
  // ── Relief ──
  ELEV:  { title: "Élévation", icon: IcMountain, desc: "Modèle d'élévation — exagération = relief ombré réglable.",
           options: [{ dataset: "copdem", index: "Élévation", label: "Copernicus DEM", res: "30 m", static: true, relief: true },
                     { dataset: "srtm", index: "Élévation", label: "SRTM", res: "30 m", static: true, relief: true }] },
  SLOPE: { title: "Pente", icon: IcMountain, desc: "Pente du terrain (°) — exagération réglable.",
           options: [{ dataset: "copdem", index: "Pente", label: "Copernicus DEM", res: "30 m", static: true, relief: true },
                     { dataset: "srtm", index: "Pente", label: "SRTM", res: "30 m", static: true, relief: true }] },
  HILLSHADE: { title: "Relief ombré (ombrage)", icon: IcMountain, desc: "Ombrage du relief — soleil (azimut/hauteur) et exagération réglables.",
           options: [{ dataset: "copdem", index: "Ombrage", label: "Copernicus DEM", res: "30 m", static: true, relief: true },
                     { dataset: "srtm", index: "Ombrage", label: "SRTM", res: "30 m", static: true, relief: true }] },
};

// Thèmes d'usage → items (indicateurs satellite + outils existants, sans distinction)
export const MENU_TREE = [
  // Imagerie brute en tête : c'est le point de départ naturel pour constater un
  // état, avant de basculer sur un indice calculé.
  { id: "imagerie", label: "Imagerie satellite", icon: IcImage, items: [
    { kind: "indicator", id: "RGBIMG" }, { kind: "indicator", id: "IRCIMG" },
    { kind: "indicator", id: "SWIRIMG" },
    { kind: "tool", id: "timelapse", label: "Timelapse", desc: "Génère un GIF animé côté serveur.", icon: IcFilm },
  ]},
  { id: "vegetation", label: "Végétation & agriculture", icon: IcSprout, items: [
    { kind: "indicator", id: "NDVI" }, { kind: "indicator", id: "EVI" }, { kind: "indicator", id: "SAVI" },
    { kind: "indicator", id: "GNDVI" }, { kind: "indicator", id: "NDRE" },
    { kind: "indicator", id: "FOREST" }, { kind: "indicator", id: "CANOPY" },
    { kind: "indicator", id: "GPP" }, { kind: "indicator", id: "LAIFAPAR" }, { kind: "indicator", id: "BIOMASS" },
    { kind: "indicator", id: "GEDI_CANOPY" }, { kind: "indicator", id: "GEDI_ELEV" },
    { kind: "indicator", id: "GEDI_COVER" }, { kind: "indicator", id: "GEDI_PAI" }, { kind: "indicator", id: "GEDI_AGB" },
    { kind: "indicator", id: "SOC" }, { kind: "indicator", id: "SOILPH" }, { kind: "indicator", id: "CLAY" },
    { kind: "tool", id: "agri", label: "Agriculture de précision", desc: "Suivi parcellaire : indices, stades, alertes.", icon: IcLeaf },
  ]},
  { id: "eau", label: "Eau & humidité", icon: IcDroplets, items: [
    { kind: "indicator", id: "NDWI" }, { kind: "indicator", id: "MNDWI" }, { kind: "indicator", id: "NDMI" },
    { kind: "indicator", id: "NDCI" }, { kind: "indicator", id: "JRC_WATER" }, { kind: "indicator", id: "SMAP" },
    { kind: "indicator", id: "SNOW" },
    { kind: "tool", id: "watershed", label: "Bassin versant", desc: "Délimite un bassin depuis un exutoire cliqué (HydroSHEDS) : limite, réseau, attributs.", icon: IcDroplets },
  ]},
  // Océanographie — thème dédié. Les items « soon » sont des données que le
  // catalogue public GEE ne contient pas : affichées grisées et documentées
  // plutôt que masquées, pour que l'absence soit explicite (choix utilisateur).
  { id: "ocean", label: "Océans & littoral", icon: IcWaves, items: [
    { kind: "indicator", id: "BATHY" },
    { kind: "indicator", id: "SST" }, { kind: "indicator", id: "SSTANOM" },
    { kind: "indicator", id: "CHLORO" }, { kind: "indicator", id: "TURBIDITY" },
    { kind: "indicator", id: "CURRENTS" }, { kind: "indicator", id: "OCEANWIND" },
    { kind: "indicator", id: "SALINITY" }, { kind: "indicator", id: "SEAICE" },
    { kind: "indicator", id: "CORAL" }, { kind: "indicator", id: "MANGROVE" },
    { kind: "soon", id: "waves", label: "Vagues (hauteur, période)", icon: IcWaves,
      note: "Hauteur/période/direction des vagues : absentes du catalogue public GEE (ERA5 y est publié sans les paramètres de vagues). Source externe requise — Copernicus Marine ou WaveWatch III." },
    { kind: "soon", id: "sealevel", label: "Niveau de la mer (altimétrie)", icon: IcTrendingUp,
      note: "Hauteur de la mer, anomalies et courants géostrophiques par altimétrie : non disponibles dans GEE. Sources externes — CMEMS / AVISO." },
  ]},
  { id: "climat", label: "Climat & température", icon: IcThermometer, items: [
    { kind: "indicator", id: "LST" }, { kind: "indicator", id: "AIRTEMP" }, { kind: "indicator", id: "PRECIP" },
    { kind: "indicator", id: "ET" }, { kind: "indicator", id: "GPMPRECIP" },
    { kind: "indicator", id: "SOLAR" }, { kind: "indicator", id: "WIND" },
    { kind: "tool", id: "timelapse", label: "Timelapse", desc: "Génère un GIF animé côté serveur.", icon: IcFilm },
  ]},
  // Météo temps réel — flux animés (radar/IR RainViewer + prévision GFS) sur une
  // frise passé→futur. Nature différente des indicateurs figés : voir WeatherPanel.
  { id: "meteo", label: "Météo & temps réel", icon: IcCloudRain, items: [
    { kind: "tool", id: "weather", label: "Météo temps réel", desc: "Radar de pluie, satellite IR mondial et prévision GFS, animés sur une frise passé→futur.", icon: IcCloudRain },
  ]},
  { id: "air", label: "Qualité de l'air", icon: IcWind, items: [
    { kind: "indicator", id: "NO2" }, { kind: "indicator", id: "CO" }, { kind: "indicator", id: "CH4" },
    { kind: "indicator", id: "O3" }, { kind: "indicator", id: "AER" },
  ]},
  { id: "urbain", label: "Urbain & aménagement", icon: IcBuilding, items: [
    { kind: "indicator", id: "NDBI" }, { kind: "indicator", id: "BSI" }, { kind: "indicator", id: "WORLDCOVER" },
    { kind: "indicator", id: "VIIRS" }, { kind: "indicator", id: "POPULATION" },
    { kind: "indicator", id: "BUILT" }, { kind: "indicator", id: "SMOD" }, { kind: "indicator", id: "DYNWORLD" },
    { kind: "tool", id: "isochrone", label: "Isochrone d'accès", desc: "Zones atteignables en un temps donné.", icon: IcRadar },
    { kind: "tool", id: "route", label: "Itinéraire", desc: "Trajet et distance entre deux points.", icon: IcNavigation },
    { kind: "tool", id: "scene3d", label: "Bâtiments 3D / Globe", desc: "Bâtiments, nuages de points, globe 3D.", icon: IcCube },
  ]},
  { id: "risques", label: "Risques & changements", icon: IcFlame, items: [
    { kind: "tool", id: "burnsev", label: "Severite d'incendie (dNBR)", desc: "Degats d'un feu par comparaison NBR avant/apres.", icon: IcFlame },
    { kind: "tool", id: "flood", label: "Cartographie des inondations", desc: "Détection radar SAR (Sentinel-1) ou modèle hauteur d'eau ; surface, population et bâti exposés.", icon: IcDroplets },
    { kind: "indicator", id: "NBR" }, { kind: "indicator", id: "NDSI" },
    { kind: "indicator", id: "BURNED" }, { kind: "indicator", id: "FIRMS" },
    { kind: "indicator", id: "SMOKE" },
    { kind: "tool", id: "change", label: "Détection de changement", desc: "Compare deux dates et isole ce qui a changé.", icon: IcDiff },
    { kind: "tool", id: "compare", label: "Comparateur A/B", desc: "Deux couches côte à côte, curseur de balayage.", icon: IcCompare },
    { kind: "tool", id: "story", label: "Story map (scrollytelling)", desc: "Raconte une histoire en chapitres animés (vues + couches) et exporte un HTML autonome.", icon: IcFilm },
  ]},
  { id: "relief", label: "Relief & 3D / LiDAR", icon: IcMountain, items: [
    { kind: "indicator", id: "ELEV" }, { kind: "indicator", id: "SLOPE" }, { kind: "indicator", id: "HILLSHADE" },
    { kind: "tool", id: "profil", label: "Profil altimétrique", desc: "Coupe altimétrique le long d'un tracé.", icon: IcTrendingUp },
    { kind: "tool", id: "lidar", label: "LiDAR — foresterie", desc: "MNT/MNS/MNH, arbres et houppiers depuis un LAS.", icon: IcTreePine },
  ]},
  { id: "planetes", label: "Planètes", icon: IcGlobe, items: [
    { kind: "tool", id: "solarsystem", label: "Système solaire (vue 3D)", desc: "Explore le Soleil, les planètes et la Lune en sphères 3D texturées.", icon: IcGlobe },
    { kind: "tool", id: "planet_sun", label: "Soleil", desc: "Notre étoile en 3D.", icon: IcSun },
    { kind: "tool", id: "planet_mercury", label: "Mercure", desc: "Planète tellurique en 3D.", icon: IcCircleDot },
    { kind: "tool", id: "planet_venus", label: "Vénus", desc: "Planète tellurique en 3D.", icon: IcCircleDot },
    { kind: "tool", id: "planet_earth", label: "Terre", desc: "Notre planète en 3D.", icon: IcGlobe },
    { kind: "tool", id: "planet_moon", label: "Lune", desc: "Satellite de la Terre en 3D.", icon: IcMoon },
    { kind: "tool", id: "planet_mars", label: "Mars", desc: "Planète rouge en 3D.", icon: IcCircleDot },
    { kind: "tool", id: "planet_jupiter", label: "Jupiter", desc: "Géante gazeuse en 3D.", icon: IcCircleDot },
    { kind: "tool", id: "planet_saturn", label: "Saturne", desc: "Géante gazeuse et ses anneaux en 3D.", icon: IcCircleDot },
    { kind: "tool", id: "planet_uranus", label: "Uranus", desc: "Géante de glaces en 3D.", icon: IcCircleDot },
    { kind: "tool", id: "planet_neptune", label: "Neptune", desc: "Géante de glaces en 3D.", icon: IcCircleDot },
  ]},
  { id: "outils", label: "Outils & données", icon: IcWrench, items: [
    { kind: "tool", id: "layers", label: "Gestionnaire de couches", desc: "Ordre, style, opacité et export des couches.", icon: IcStack },
    { kind: "tool", id: "vectorcat", label: "Catalogue vectoriel", desc: "Cherche et ajoute des données vectorielles (limites, routes, rivières, séismes…).", icon: IcBoxes },
    { kind: "tool", id: "stac", label: "Navigateur STAC / COG", desc: "Cherche des scènes satellite (Sentinel-2…) sur l'emprise et ajoute leur aperçu COG.", icon: IcSatellite },
    { kind: "tool", id: "sql", label: "SQL Workspace", desc: "Éditeur SQL spatial (DuckDB) sur vos couches → résultat en carte.", icon: IcTable },
    { kind: "tool", id: "rasteranalysis", label: "Analyse raster (zonal + calc)", desc: "Statistiques zonales et calculatrice (map algebra) sur un GeoTIFF importé.", icon: IcGrid },
    { kind: "tool", id: "rastervec", label: "Vectorisation raster (polygones + contours)", desc: "Transforme un GeoTIFF en polygones (par classes) ou en courbes de niveau.", icon: IcHexagon },
    { kind: "tool", id: "spatialstats", label: "Stats spatiales (Moran, hotspots)", desc: "Autocorrélation spatiale (Moran) et points chauds/froids (Getis-Ord Gi*) d'un champ.", icon: IcCircleDot },
    { kind: "tool", id: "vectorviz", label: "Chaleur & clusters", desc: "Carte de chaleur (densité) et regroupement de points. Hexagones/flux : voir Analyse spatiale.", icon: IcRadar },
    { kind: "tool", id: "viewshed", label: "Analyse de visibilité (viewshed)", desc: "Ce qui est visible depuis un point, sur le relief (MNT mondial ~30 m).", icon: IcMountain },
    { kind: "tool", id: "georef", label: "Géoréférenceur (caler une image)", desc: "Cale un plan scanné ou une photo sur la carte via des points d'appui (affine/projective).", icon: IcMap },
    { kind: "tool", id: "bivariate", label: "Carte bivariée (2 variables)", desc: "Croise deux variables en une seule palette.", icon: IcGrid },
    { kind: "tool", id: "stats", label: "Statistiques", desc: "Statistiques descriptives d'une couche.", icon: IcBarChart },
    { kind: "tool", id: "join", label: "Jointure attributaire", desc: "Rapatrie les colonnes d'un CSV vers une couche.", icon: IcTable },
    { kind: "tool", id: "spatial", label: "Analyse spatiale", desc: "Intersections, jointures, agrégations.", icon: IcVenn },
    { kind: "tool", id: "classif", label: "Classification supervisée", desc: "Entraîne un modèle sur vos échantillons.", icon: IcClassif },
    { kind: "tool", id: "editor", label: "Éditeur vectoriel", desc: "Dessine et modifie des entités vectorielles.", icon: IcEdit },
    { kind: "tool", id: "database", label: "Base de données", desc: "Interroge et importe depuis DuckDB.", icon: IcDatabase },
    { kind: "tool", id: "ogc", label: "Services OGC / WMS", desc: "Connecte un flux WMS / WFS / WMTS externe.", icon: IcServer },
    { kind: "tool", id: "osm", label: "Import OSM", desc: "Extrait des objets OpenStreetMap par thème.", icon: IcOSM },
    { kind: "tool", id: "measure_dist", label: "Mesure distance", desc: "Longueur d'une ligne sur la carte.", icon: IcRulerTool },
    { kind: "tool", id: "measure_area", label: "Mesure surface", desc: "Superficie d'un polygone tracé.", icon: IcHexagon },
    { kind: "tool", id: "buffer", label: "Zone tampon", desc: "Zone d'influence autour d'une entité.", icon: IcCircleDot },
    { kind: "tool", id: "draw", label: "Dessin libre", desc: "Croquis libre : points, lignes, polygones.", icon: IcPencil },
    { kind: "tool", id: "gee", label: "GEE — mode avancé", desc: "Accès direct au catalogue Earth Engine.", icon: IcSatellite },
    { kind: "tool", id: "projections", label: "Projections du monde", desc: "Composeur de carte : projection, habillage, PDF.", icon: IcMap },
  ]},
];
